// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA3yIXylf0o88HhfzJtcU_v9SqkE4DuYg',
    appId: '1:190440784483:web:516f84240e30376d376e56',
    messagingSenderId: '190440784483',
    projectId: 'jarvis-1e093',
    authDomain: 'jarvis-1e093.firebaseapp.com',
    storageBucket: 'jarvis-1e093.firebasestorage.app',
    measurementId: 'G-77RQL6D1PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCktWY4anp-9Zyf_GQ8o-6GHgRrYRshR1Y',
    appId: '1:190440784483:android:00b54f299aabc4dd376e56',
    messagingSenderId: '190440784483',
    projectId: 'jarvis-1e093',
    storageBucket: 'jarvis-1e093.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA3yIXylf0o88HhfzJtcU_v9SqkE4DuYg',
    appId: '1:190440784483:web:c7271b650fe38e79376e56',
    messagingSenderId: '190440784483',
    projectId: 'jarvis-1e093',
    authDomain: 'jarvis-1e093.firebaseapp.com',
    storageBucket: 'jarvis-1e093.firebasestorage.app',
    measurementId: 'G-H80C9DTM2B',
  );
}
